// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestNavigateTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testNavigate() {
    driver.Navigate().GoToUrl("https://sia0.github.io/Apni-Dukaan/contactus.html");
    driver.Manage().Window.Size = new System.Drawing.Size(780, 820);
    driver.FindElement(By.LinkText("Home")).Click();
    driver.FindElement(By.CssSelector(".navbar-toggler-icon")).Click();
    driver.FindElement(By.LinkText("Login")).Click();
  }
}
