# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestNavigate():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testNavigate(self):
    self.driver.get("https://sia0.github.io/Apni-Dukaan/contactus.html")
    self.driver.set_window_size(780, 820)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
  
