# Generated by Selenium IDE
import pytest
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Testing(unittest.TestCase):
  def test_testNavigate(self):
    self.driver = webdriver.Chrome()
    self.driver.get("https://christineleong1711.github.io/Apni-Dukaan/")
    self.driver.set_window_size(1296, 705)
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(5) > .nav-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".material-icons").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(5) > .nav-link").click()
    self.driver.find_element(By.LINK_TEXT, "Offers").click()
    self.driver.find_element(By.LINK_TEXT, "About Us").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(3) > .nav-link").click()
    self.driver.find_element(By.LINK_TEXT, "About Us").click()
    self.driver.find_element(By.LINK_TEXT, "FAQ").click()
    self.driver.find_element(By.LINK_TEXT, "About Us").click()
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Mobile").click()
    self.driver.find_element(By.LINK_TEXT, "About Us").click()
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "TV/Appliances").click()
    self.driver.find_element(By.LINK_TEXT, "About Us").click()
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Furniture").click()
    self.driver.find_element(By.LINK_TEXT, "About Us").click()
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Baby/Kids").click()
    self.driver.find_element(By.LINK_TEXT, "About Us").click()
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Stationery").click()
    self.driver.find_element(By.LINK_TEXT, "About Us").click()
    self.driver.quit()
  
if __name__ == "__main__":
 unittest.main()