# Generated by Selenium IDE
import pytest
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFormValidation(unittest.TestCase):
  def test_FormValidation(self):
    self.driver = webdriver.Chrome()
    self.driver.get("https://sia0.github.io/Apni-Dukaan/")
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(3) > .nav-link").click()
    self.driver.find_element(By.ID, "validationCustom01").click()
    self.driver.find_element(By.ID, "validationCustom01").send_keys("Sia Chong Perng5")
    element = self.driver.find_element(By.CSS_SELECTOR, ".input-container:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    #invMsgClass = driver.find_element(By.ID, "invalidNameMsg").getAttribute("class")
    #print(invMsgClass)
    print("Enter")
    #self.assertTrue(invalid, "Should be display")
    self.driver.find_element(By.ID, "validationCustom01").click()
    self.driver.find_element(By.ID, "validationCustom01").send_keys("Sia Chong Perng")
    self.driver.find_element(By.CSS_SELECTOR, ".contact-table").click()
    self.driver.find_element(By.ID, "validationCustom02").click()
    self.driver.find_element(By.ID, "validationCustom02").send_keys("chongperng")
    self.driver.find_element(By.CSS_SELECTOR, ".contact-table").click()
    self.driver.find_element(By.ID, "validationCustom02").click()
    self.driver.find_element(By.ID, "validationCustom02").send_keys("chongperngsia@hotmail")
    self.driver.find_element(By.CSS_SELECTOR, ".contact-table").click()
    self.driver.find_element(By.ID, "validationCustom02").click()
    self.driver.find_element(By.ID, "validationCustom02").send_keys("chongperngsia@hotmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".contact-table").click()
    self.driver.find_element(By.ID, "submit-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-container:nth-child(3)").click()
    self.driver.find_element(By.ID, "validationCustom03").click()
    self.driver.find_element(By.ID, "validationCustom03").send_keys("Can I have my product advertise on this website?")
    self.driver.find_element(By.ID, "submit-btn").click()
    self.driver.quit()

if __name__ == "__main__":
 unittest.main()